name: tax_advisory_app
description: A new Flutter project.
version: 1.0.0+3
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.11.0
  firebase_auth: ^4.4.0
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  connectivity_plus: ^5.0.2
  custom_line_indicator_bottom_navbar: ^0.0.8
  stylish_bottom_bar: ^1.1.0
  http: ^1.2.1
  get: ^4.6.6
  shared_preferences: ^2.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterExtraBold.ttf
          weight: 800
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterLight.ttf
          weight: 300
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: Commissioner
      fonts:
        - asset: assets/fonts/CommissionerRegular.ttf
          weight: 400
        - asset: assets/fonts/CommissionerBold.ttf
          weight: 700
